### PR TITLE
Feature/updated database docs

### PR DESCRIPTION
**Pull request by roll**

### CODE REVIEW

**Comment by vitorbaptista** [comment]
Everything looks fine, I just didn't understand why you linked to a specific migration.

**Comment by roll** [comment]
Kinda versioning - so this docs is actual for this state of `database`.

**Comment by vitorbaptista** [comment]
In that case, I would suggest changing to something like `Last updated on migration 20160415172210`.

**Comment by roll** [comment]
I've already tried  `This document is actual for this migration:` but I like your version better. So updated to `Last updated on migration 20160415172210`

**Pull request merged**
