### PR TITLE
Adjust the garbage collector to reduce memory footprint

### PR DESCRIPTION
**Pull request by nightsh**
Attempting to reduce the issues we have with memory load on the API. Step one is to slightly adjust the way Node's GC works and observe if there is any impact.

### CODE REVIEW

**Comment by nightsh** [comment]
Oh, can I do that? I didn't know, honestly.

Do you know whether the main idea is to leave it on heroku, or switch to our own infra hosting instead? Not sure what are the next steps regarding this, therefore I don't know how much should I research heroku-based optimizations vs more subtle ways of improving performance.

**Comment by pwalsh** [comment]
it will move to our own hosting as soon as @vitorbaptista is back

**Comment by pwalsh** [comment]
and I don't think you should investigate performance optimisations at all. if you have a memory problem, tell me and we'll increase the resources on heroku in the short term

**Comment by nightsh** [comment]
Oh, okay then, feel free to increase the memory then, it's hitting memory quota multiple times a day, e.g.

> Dec 19 23:34:51 opentrials-api heroku/web.1: Error R14 (Memory quota exceeded) 

And we can probably kill this PR afterwards.

**Comment by pwalsh** [comment]
@nightsh you can kill the PR.

**Pull request closed without merging**
