### PR TITLE
[#186] Sort trials results by registration_date and _score

### PR DESCRIPTION
**Pull request by vitorbaptista**
Fixes opentrials/opentrials#186

### CODE REVIEW

**Comment by vitorbaptista** [comment]
@roll Please, review. To see the result of these changes, compare https://ot-api-next-pr-58.herokuapp.com/v1/search with http://api.next.opentrials.net/v1/search

**Comment by roll** [comment]
@vitorbaptista 
http://api.next.opentrials.net/v1/search - ohh SCHEMA_VALIDATION_FAILED again

**Comment by vitorbaptista** [comment]
@roll fixed, just needed `npm run reindex`

**Comment by roll** [comment]
:+1:

**Pull request merged**
